reference-quality: fix ref-risk classify
In the previous patch I was calling the wrong function which results in a bunch of errors

TypeError: classify() missing 1 required positional argument: 'revision'
Change-Id: Icec8f4ab4fd0e5e27560c5222bae6dda23138340