revertrisk-multilingual: Hotfix on validation_json.
This change fixes the error:
    if self.event_key in inputs:
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'

Change-Id: I7f852b1c9c8e820edf7b175cb2a019e803019263