logo_detection: bump kserve to 0.15.2 for pydantic v2 compatibility.
This solves the CI issue on: https://gerrit.wikimedia.org/r/c/machinelearning/liftwing/inference-services/+/1326330
Error message: """pydantic-settings 2.8.1 depends on pydantic>=2.7.0
fastapi 0.95.x (pulled in by kserve==0.11.2) depends on pydantic<2.0.0
ERROR: ResolutionImpossible"""

Bug: T435946
Change-Id: I23d32ce72420ed35e2f4ed7ad536a7cbb6df47eb