ores-legacy: simplify test in test_liftwing.py
When I ran `pytest` I found this problem:

aiohttp.client_exceptions.ClientConnectorError: <exception str() failed>

After a big of digging I noticed that aiohttp's ClientConnectorError
takes as first parameter something that represents its proxy status
etc.., not a simple string, hence the error while checking (in __str__)
if self.ssl was there. I changed the Exception type to something
simpler, IIUC it shouldn't change the semantic of the test.

Bug: T337287
Change-Id: Iee6e7d6116db834e202dcca833a10c86b95a313a